# Generated by Django 5.2.13 on 2026-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_patient_allergies_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WAITING', 'Waiting in Lobby'), ('LATE', 'Late'), ('IN_CONSULTATION', 'In Consultation'), ('CLEARED', 'Cleared / Paid'), ('NO_SHOW', 'No-Show')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
