# Generated by Django 5.2.13 on 2026-04-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_appointment_status_alter_patient_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=50)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet(s)'), ('Capsule', 'Capsule(s)'), ('Tbsp', 'Tablespoon(s)'), ('Tsp', 'Teaspoon(s)'), ('Drop', 'Drop(s)'), ('Application', 'Application(s)'), ('Patch', 'Patch(es)')], default='Tablet', max_length=20)),
                ('frequency', models.CharField(help_text='e.g., 3 times a day', max_length=100)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.appointment')),
            ],
        ),
    ]
